/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SesionFrame;

import javax.swing.JButton;

/**
 *
 * @author marti
 */
public class ventanaAlumno extends javax.swing.JFrame {

    /**
     * Creates new form ventanaAlumno
     */
    public ventanaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExportarNotas = new javax.swing.JButton();
        btnMostrarNotas = new javax.swing.JButton();
        btnMateriales = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido Alumn@");

        btnExportarNotas.setText("Exportar Notas");

        btnMostrarNotas.setText("Mostrar Notas");

        btnMateriales.setText("Ver Materiales");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(btnMateriales)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExportarNotas)
                        .addGap(36, 36, 36)
                        .addComponent(btnMostrarNotas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSalir)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarNotas)
                    .addComponent(btnExportarNotas)
                    .addComponent(btnMateriales))
                .addGap(35, 35, 35)
                .addComponent(btnSalir)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarNotas;
    private javax.swing.JButton btnMateriales;
    private javax.swing.JButton btnMostrarNotas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnExportarNotas() {
        return btnExportarNotas;
    }

    public JButton getBtnMateriales() {
        return btnMateriales;
    }

    public JButton getBtnMostrarNotas() {
        return btnMostrarNotas;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }
    
}
