/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SesionFrame;

import javax.swing.JButton;

/**
 *
 * @author marti
 */
public class ventanaProfesor extends javax.swing.JFrame {

    /**
     * Creates new form ventanaProfesor
     */
    public ventanaProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVerDatos = new javax.swing.JButton();
        btnVerAlumno = new javax.swing.JButton();
        btnAlumnoPromedios = new javax.swing.JButton();
        btnNotaAceptableInaceptable = new javax.swing.JButton();
        btnAgregarNota = new javax.swing.JButton();
        btnAgregarMaterial = new javax.swing.JButton();
        btnCambiarNota = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminarMaterial = new javax.swing.JButton();
        btnEliminarNota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aula Virtual");

        jLabel2.setText("Profesor");

        btnVerDatos.setText("Ver datos");

        btnVerAlumno.setText("Ver datos de alumno");

        btnAlumnoPromedios.setText("Alumnos con promedio mas bajo y alto");

        btnNotaAceptableInaceptable.setText("Notas de alumno por mas aceptables e inaceptables");

        btnAgregarNota.setText("Agregar nota");

        btnAgregarMaterial.setText("Agregar Material");

        btnCambiarNota.setText("Cambiar nota");

        btnSalir.setText("Salir");

        btnEliminarMaterial.setText("Eliminar Material");

        btnEliminarNota.setText("Eliminar Nota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarNota)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarMaterial)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMaterial)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarNota)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNotaAceptableInaceptable)
                                .addGap(18, 18, 18)
                                .addComponent(btnCambiarNota))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(btnSalir)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVerDatos)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlumnoPromedios))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDatos)
                    .addComponent(btnVerAlumno)
                    .addComponent(btnAlumnoPromedios))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotaAceptableInaceptable)
                    .addComponent(btnCambiarNota))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMaterial)
                    .addComponent(btnAgregarNota)
                    .addComponent(btnEliminarMaterial)
                    .addComponent(btnEliminarNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMaterial;
    private javax.swing.JButton btnAgregarNota;
    private javax.swing.JButton btnAlumnoPromedios;
    private javax.swing.JButton btnCambiarNota;
    private javax.swing.JButton btnEliminarMaterial;
    private javax.swing.JButton btnEliminarNota;
    private javax.swing.JButton btnNotaAceptableInaceptable;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerAlumno;
    private javax.swing.JButton btnVerDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAgregarMaterial() {
        return btnAgregarMaterial;
    }

    public JButton getBtnAgregarNota() {
        return btnAgregarNota;
    }

    public JButton getBtnAlumnoPromedios() {
        return btnAlumnoPromedios;
    }

    public JButton getBtnCambiarNota() {
        return btnCambiarNota;
    }

    public JButton getBtnNotaAceptableInaceptable() {
        return btnNotaAceptableInaceptable;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public JButton getBtnVerAlumno() {
        return btnVerAlumno;
    }

    public JButton getBtnVerDatos() {
        return btnVerDatos;
    }

    public JButton getBtnEliminarMaterial() {
        return btnEliminarMaterial;
    }

    public JButton getBtnEliminarNota() {
        return btnEliminarNota;
    }
    
}
